/*
 * Name: Dylan Harvey
 * Date Submitted: 9/--/2024
 * Lab Section: 005
 * Assignment Name: Lab 2: Infix to Postfix Conversion
 */

#include <iostream>
#include <string>
#include <stack>

using namespace std;

// Helper function for operator precedence
int precedence(const string &op) {
    if (op == "+" || op == "-") return 1;
    if (op == "*" || op == "/" || op == "%") return 2;
    return 0; // For non-operators or parentheses
}

//Converts an infix arithmetic expression into postfix
//The function takes 3 parameters
//First parameter: array of strings for infix expression
//    each string is either an integer number or operator symbol
//Second parameter: number of strings in infix expression
//Third parameter: array of strings for postfix expression
//    generated by function, same format as first parameter
//    assumes that postfix is at least the size of postfix
//Return value: int, number of strings in postfix expression
//    Returns 0 if an error is encountered when converting expression
//    An error occurs with a mismatched parenthesis, e.g. ( ( ) or ( ) ) etc.
//Operator symbols:
// ( : left parenthesis, all operations between this and ")" take place first
// ) : right parenthesis, all op.s back to previous "(" take place first
// * : multiplication, higher precedence - takes place before "+" and "-"
// / : division, higher precedence - takes place before "+" and "-"
// % : remainder, higher precedence - takes place before "+" and "-"
// + : addition, lower precedence - takes place after "*" , "/" , "%"
// - : subtraction, lower precedence - takes place after "*" , "/" , "%"
//The function is not specified to work with any other operator symbols
//Any string in infix may be assumed to be an integer operand if none
// of the above symbols
int infixToPostfix(string infix[], int length, string postfix[]) {
    stack<string> operators;
    int postfixIndex = 0;

    for (int i = 0; i < length; i++) {
        string token = infix[i];

        if (isdigit(token[0])) { // If operand (number)
            postfix[postfixIndex++] = token; // Add number to postfix output
        } else if (token == "(") {
            operators.push(token); // Push '(' to the stack of operators
        } else if (token == ")") {
            // Pop from stack until ')' is found
            while (!operators.empty() && operators.top() != "(") {
                postfix[postfixIndex++] = operators.top();
                operators.pop();
            }
            if (operators.empty()) {
                return 0; // Mismatched parentheses
            }
            operators.pop(); // Pop the '('
        } else {
            while (!operators.empty() && precedence(operators.top()) >= precedence(token)) {
                postfix[postfixIndex++] = operators.top();
                operators.pop();
            }
            operators.push(token); // Push current operator to the stack
        }
    }
    
    // Pop all remaining operators from the stack
    while (!operators.empty()) {
        if (operators.top() == "(") {
            return 0; // Mismatched parentheses
        }
        postfix[postfixIndex++] = operators.top();
        operators.pop();
    }

    return postfixIndex; // Return the number of tokens in postdix (length)
}

//Main function to test infixToPostfix()
//Should convert 2 + 3 * 4 + ( 5 - 6 + 7 ) * 8
//            to 2 3 4 * + 5 6 - 7 + 8 * +

// COMMENTED OUT MAIN FOR TESTS/AUTOGRADER
/*
int main() {
    string infixExp[] = {"2", "+", "3", "*", "4", "+", "(",
                         "5", "-", "6", "+", "7", ")", "*",
                         "8"};
    string postfixExp[15];
    int postfixLength;

    cout << "Infix expression: ";
    for (int i=0; i<15; i++) {
        cout << infixExp[i] << " ";
    }
    cout << endl;
    cout << "Length: 15" << endl << endl;

    postfixLength = infixToPostfix(infixExp, 15, postfixExp);

    cout << "Postfix expression: ";
    for (int i=0; i<postfixLength; i++) {
        cout << postfixExp[i] << " ";
    }
    cout << endl;
    cout << "Length: " << postfixLength << endl;
    
    return 0;
}
*/